### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SolanaGO** [Yuteoctober/wins95Portfolio#3]
Hello, I would like to ask what files and codes should be modified if I need to change the name of the desktop icon but do not change the image.

**Comment by Yuteoctober** [comment]
every icons are pulled from icon.json

**Comment by Yuteoctober** [comment]
and if you change the name on icon.json, you also need to change the name in this function called ObjectState() in App.jsx because all the open / close and other functionalities are tied to this function
